### ISSUE TITLE
Charmap Issue

### ISSUE THREAD

**Issue by Jaxonos** [Jertzukka/dlensExporter#5]
I don't really know, what I am looking at. This is the error that appears. Thank you for help. 
![Screenshot 2023-10-17 170611](https://github.com/Jertzukka/dlensExporter/assets/114451531/e6df14bf-2d04-4d39-a79b-f36351ef29aa)

[DLENS BACKUP FILE.zip](https://github.com/Jertzukka/dlensExporter/files/12926205/DLENS.BACKUP.FILE.zip)

**Comment by Jaxonos** [comment]
[17_10_2023-17_04_59.csv](https://github.com/Jertzukka/dlensExporter/files/12925411/17_10_2023-17_04_59.csv)

This is the output file when it stops.

**Comment by Jertzukka** [comment]
@Jaxonos

Thank you for reporting it, this was actually fixed in #4 but I didn't remember to update the builds in releases. I've done this now. The latest 1.2 release is now up-to-date with master branch https://github.com/Jertzukka/dlensExporter/releases
